apiVersion: 1

datasources:
  - name: InfluxDB_IoT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    
    jsonData:
      version: "2"
      organization: IoT_Organization
      defaultBucket: sensor_data
      tlsSkipVerify: true
      httpMode: POST
      maxSeries: 1000
      timeout: 60
      
    secureJsonData:
      token: iot-super-secret-token-2024
