apiVersion: 1

datasources:
  - name: InfluxDB_IoT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    uid: influxdb-iot-datasource
    editable: true
    
    jsonData:
      version: "Flux"
      organization: IoT_Organization
      defaultBucket: sensor_data
      tlsSkipVerify: true
      httpMode: POST
      
    secureJsonData:
      token: iot-super-secret-token-2024
